add ACM governance policy propagator CPU/Memory/Network
akrzos/acm-deploy-load pull request #12
Opened 2023-11-07 21:39 UTC by tingxueca

2023-11-07 21:44 UTC, akrzos requested changes
Lets get those graphs added to the acm_data list so we have the graphs shown in the report.html.

2023-11-07 21:44 UTC, akrzos commented on acm-deploy-load/analyze-prometheus.py
> +  # ACM governance policy propagator CPU/Memory/Network
We will need entries for each new graph in the list named `acm_data` on line 155 for each graph:
```
cpu-acm-grc-policy-prop
mem-acm-grc-policy-prop
net-rcv-acm-grc-policy-prop
net-xmt-acm-grc-policy-prop
```
That is so the graphs are added into the report.html.  In the future I hope to restructure that such that when adding new queries, we generate that list data so I don't have to manage it.

2023-11-09 19:22 UTC, tingxueca commented on acm-deploy-load/analyze-prometheus.py
> +  # ACM governance policy propagator CPU/Memory/Network
thanks, added them

2023-11-10 14:49 UTC, akrzos approved these changes

2023-11-10 14:50 UTC, merged